// Intake controller. Two ways to add leads, both posting to the backend which
// scores + ranks them; the LLM (when configured) parses the file, follows the
// prompt, and writes the per-lead playbook.

import { api } from './api.js';
import { toast, busy } from './toast.js';
import { esc, fmtInt } from './format.js';

const $ = (id) => document.getElementById(id);

let fileContent = null;
let fileName = null;

// ── AI status banner ─────────────────────────────────────────────────────────
async function showAiStatus() {
  try {
    const meta = await api.getMeta();
    const llm = meta.llm || {};
    const banner = $('aiStatus');
    if (!banner) return;
    if (llm.provider === 'mock') {
      banner.innerHTML = '⚠️ <strong>AI is in mock mode</strong> (no LLM key). Leads are still scored &amp; ranked by the models; pitch/outreach use a deterministic fallback.';
      banner.className = 'panel-sub';
      banner.style.color = 'var(--warning)';
    } else {
      banner.innerHTML = `✨ <strong>AI enabled</strong> — ${esc(llm.provider)} · ${esc(llm.model || '')}. The model will generate per-lead insights.`;
      banner.style.color = 'var(--accent4)';
    }
  } catch {
    /* dashboard handles connection errors; intake stays usable */
  }
}

// ── File handling (read client-side as text) ─────────────────────────────────
function wireFile() {
  const input = $('fileInput');
  const zone = $('dropzone');
  const pill = $('filePill');

  function setFile(file) {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      fileContent = String(reader.result || '');
      fileName = file.name;
      pill.querySelector('.file-name').textContent = `${file.name} (${fmtInt(fileContent.length)} chars)`;
      pill.classList.add('show');
    };
    reader.onerror = () => toast('Could not read file', 'error');
    reader.readAsText(file);
  }

  zone.addEventListener('click', () => input.click());
  input.addEventListener('change', () => setFile(input.files[0]));
  ['dragover', 'dragenter'].forEach((ev) =>
    zone.addEventListener(ev, (e) => { e.preventDefault(); zone.classList.add('drag'); }));
  ['dragleave', 'drop'].forEach((ev) =>
    zone.addEventListener(ev, (e) => { e.preventDefault(); zone.classList.remove('drag'); }));
  zone.addEventListener('drop', (e) => setFile(e.dataTransfer.files[0]));

  pill.querySelector('button').addEventListener('click', () => {
    fileContent = null; fileName = null;
    input.value = '';
    pill.classList.remove('show');
  });
}

function showResult(el, lines) {
  el.innerHTML = lines.map(([k, v]) => `<div class="result-line"><span>${esc(k)}</span><span>${esc(v)}</span></div>`).join('')
    + '<a class="btn btn-primary btn-sm" href="index.html" style="margin-top:14px;display:inline-flex;">Open dashboard →</a>';
  el.classList.add('show');
}

// ── AI intake (prompt + file) ────────────────────────────────────────────────
function wireIntake() {
  const btn = $('intakeSubmit');
  btn.addEventListener('click', async () => {
    const prompt = $('promptInput').value.trim();
    const countRaw = $('countInput').value.trim();
    const count = countRaw ? Number(countRaw) : undefined;
    const enrich = $('intakeEnrich').checked;

    if (!prompt && !fileContent) {
      toast('Add a prompt or attach a file first', 'error');
      return;
    }

    const body = { prompt: prompt || undefined, count };
    if (fileContent) body.file = { content: fileContent, type: 'auto' };

    const restore = busy(btn, enrich ? 'Importing + AI…' : 'Importing…');
    try {
      const res = await api.intake(body, { enrich });
      const meta = res.intake || {};
      showResult($('intakeResult'), [
        ['Imported', fmtInt(res.imported)],
        ['From file', fmtInt(res.from_file)],
        ['Generated by AI', fmtInt(res.generated)],
        ['AI used', meta.llm_used ? 'yes' : 'no (deterministic)'],
        ['Estimated metrics for', `${(meta.estimated_metrics_for || []).length} lead(s)`],
      ]);
      toast(`Imported ${res.imported} lead(s)`, 'success');
    } catch (e) {
      toast(`Intake failed: ${e.message}`, 'error');
    } finally {
      restore();
    }
  });
}

// ── Manual single-lead add ───────────────────────────────────────────────────
function wireManual() {
  const btn = $('manualSubmit');
  btn.addEventListener('click', async () => {
    const metrics = {};
    for (const f of ['licensed_users', 'active_users', 'app_mix_score', 'avg_hours_saved_per_user_month', 'loaded_hourly_cost_usd', 'license_cost_month_usd', 'company_size']) {
      const v = $(`m_${f}`).value.trim();
      if (v !== '') metrics[f] = Number(v);
    }
    const lead = {
      company_name: $('c_company').value.trim() || 'Untitled Account',
      industry: $('c_industry').value.trim(),
      contact: {
        name: $('c_contact').value.trim(),
        title: $('c_title').value.trim(),
        email: $('c_email').value.trim(),
      },
      metrics,
    };
    const enrich = $('manualEnrich').checked;

    const missing = ['licensed_users', 'active_users', 'app_mix_score', 'avg_hours_saved_per_user_month', 'loaded_hourly_cost_usd', 'license_cost_month_usd', 'company_size']
      .filter((f) => metrics[f] === undefined || Number.isNaN(metrics[f]));
    if (missing.length) {
      toast(`Missing metrics: ${missing.join(', ')}`, 'error');
      return;
    }

    const restore = busy(btn, enrich ? 'Scoring + AI…' : 'Scoring…');
    try {
      const res = await api.createLead(lead, { enrich });
      const s = res.lead.scoring || {};
      showResult($('manualResult'), [
        ['Company', res.lead.company_name],
        ['Lead score', Math.round(s.lead_score)],
        ['Priority', s.priority],
        ['ROI', `${Number(s.finance_roi_percent_month).toFixed(1)}%`],
        ['AI insights', res.lead.enrichment ? 'generated' : 'not requested'],
      ]);
      toast('Lead added', 'success');
    } catch (e) {
      toast(`Add failed: ${e.message}`, 'error');
    } finally {
      restore();
    }
  });
}

showAiStatus();
wireFile();
wireIntake();
wireManual();
