// Lead detail drawer. A THIN renderer of backend data: model scores from
// lead.scoring and the sales playbook from lead.enrichment (LLM). It never
// fabricates insights — if enrichment is missing it offers a button that asks
// the backend (LLM) to generate it via /analyze.

import { api } from './api.js';
import { store } from './store.js';
import { toast, busy } from './toast.js';
import {
  fmtUsd, fmtInt, fmtPct, n, esc, escMultiline, healthColor, adoptionPct, orDash,
} from './format.js';

let overlay;
let onChangeCb = () => {};

function ensureOverlay() {
  if (overlay) return overlay;
  overlay = document.createElement('div');
  overlay.className = 'company-menu-overlay hidden';
  overlay.setAttribute('aria-hidden', 'true');
  overlay.innerHTML = `
    <div class="company-menu" role="dialog" aria-modal="true">
      <div class="company-menu-header">
        <div>
          <div id="drawerTitle" class="menu-title">Lead</div>
          <div id="drawerSub" class="card-sub" style="margin:4px 0 0 0;"></div>
        </div>
        <button id="drawerClose" class="menu-close" type="button">Close</button>
      </div>
      <div id="drawerBody"></div>
    </div>`;
  document.body.appendChild(overlay);

  overlay.querySelector('#drawerClose').addEventListener('click', close);
  overlay.addEventListener('click', (e) => { if (e.target === overlay) close(); });
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && !overlay.classList.contains('hidden')) close();
  });
  return overlay;
}

function close() {
  if (!overlay) return;
  overlay.classList.add('hidden');
  overlay.setAttribute('aria-hidden', 'true');
}

function listBlock(title, items, cls = '') {
  if (!Array.isArray(items) || !items.length) return '';
  const lis = items.map((x) => `<li>${esc(x)}</li>`).join('');
  return `<div class="enrich-block"><h4>${esc(title)}</h4><ul class="enrich-list ${cls}">${lis}</ul></div>`;
}

function scoresHtml(lead) {
  const s = lead.scoring || {};
  const m = lead.metrics || {};
  const rows = [
    ['Lead score', Number.isFinite(Number(s.lead_score)) ? Math.round(s.lead_score) : '—'],
    ['Priority', orDash(s.priority)],
    ['Rank', orDash(s.rank)],
    ['ROI (finance)', Number.isFinite(Number(s.finance_roi_percent_month)) ? fmtPct(s.finance_roi_percent_month, 1) : '—'],
    ['Net value / mo', Number.isFinite(Number(s.net_value_month_usd)) ? fmtUsd(s.net_value_month_usd) : '—'],
    ['Waste / mo', Number.isFinite(Number(s.waste_license_cost_month_usd)) ? fmtUsd(s.waste_license_cost_month_usd) : '—'],
    ['Expansion', s.expansion_recommend == null ? '—' : `${s.expansion_recommend ? 'Recommended' : 'Hold'} (${fmtPct(s.expansion_confidence_pct, 1)})`],
    ['Adoption', fmtPct(adoptionPct(m), 1)],
  ];
  return `
    <div class="menu-card opportunity">
      <h4>Model Scores</h4>
      ${rows.map(([k, v]) => `<div class="menu-row"><span class="menu-key">${esc(k)}</span><span class="menu-value">${esc(v)}</span></div>`).join('')}
    </div>`;
}

function enrichmentHtml(lead) {
  const e = lead.enrichment;
  if (!e || (!e.sales_pitch && !e.summary)) {
    return `
      <div class="empty-enrich">
        <div>No AI insights yet for this lead.</div>
        <button class="btn btn-accent btn-sm" data-act="analyze" style="margin-top:10px;">✨ Generate AI insights</button>
      </div>`;
  }
  const outreach = e.outreach && (e.outreach.subject || e.outreach.body)
    ? `<div class="enrich-block"><h4>Outreach email</h4>
         <div class="outreach-box">
           <div class="outreach-subject">${esc(e.outreach.subject || '(no subject)')}</div>
           <div class="outreach-body">${escMultiline(e.outreach.body || '')}</div>
         </div></div>`
    : '';

  return `
    ${e.health ? `<div class="enrich-block"><span class="health-chip" style="color:${healthColor(e.health)}">● ${esc(e.health)} health</span></div>` : ''}
    ${e.summary ? `<div class="enrich-block"><h4>Summary</h4><p>${esc(e.summary)}</p></div>` : ''}
    ${e.sales_pitch ? `<div class="enrich-block"><h4>Sales pitch</h4><p>${escMultiline(e.sales_pitch)}</p></div>` : ''}
    ${listBlock('Talking points', e.talking_points)}
    ${listBlock('Value drivers', e.value_drivers)}
    ${listBlock('Risks', e.risks, 'risk-list')}
    ${listBlock('Recommended actions', e.recommended_actions)}
    ${outreach}
    ${e.model ? `<div class="ai-source">Generated by: ${esc(e.model)}</div>` : ''}`;
}

function stageSelect(lead, stages) {
  const opts = (stages || []).map(
    (s) => `<option value="${esc(s)}" ${s === lead.stage ? 'selected' : ''}>${esc(s)}</option>`,
  ).join('');
  return `<select id="drawerStage" class="btn btn-sm" style="padding-right:8px;">${opts}</select>`;
}

function render(lead) {
  const body = overlay.querySelector('#drawerBody');
  const s = lead.scoring || {};
  const contact = lead.contact || {};
  const hasEnrich = lead.enrichment && (lead.enrichment.sales_pitch || lead.enrichment.summary);
  const stages = store.meta?.pipeline_stages || ['New', 'Qualified', 'Contacted', 'Engaged', 'Proposal', 'Won', 'Lost'];

  overlay.querySelector('#drawerTitle').textContent = lead.company_name || 'Lead';
  overlay.querySelector('#drawerSub').textContent =
    `${orDash(lead.industry)} · Priority ${orDash(s.priority)} · Score ${Number.isFinite(Number(s.lead_score)) ? Math.round(s.lead_score) : '—'}`;

  body.innerHTML = `
    <div class="drawer-actions">
      <button class="btn btn-accent btn-sm" data-act="analyze">${hasEnrich ? '🔄 Re-analyze' : '✨ Generate AI insights'}</button>
      <button class="btn btn-sm" data-act="outreach">✉️ Draft email</button>
      ${stageSelect(lead, stages)}
      <button class="btn btn-danger btn-sm" data-act="delete">Delete</button>
    </div>

    <div class="menu-grid">
      <div class="menu-card contact">
        <h4>Contact</h4>
        <div class="menu-row"><span class="menu-key">Name</span><span class="menu-value">${esc(orDash(contact.name))}</span></div>
        <div class="menu-row"><span class="menu-key">Title</span><span class="menu-value">${esc(orDash(contact.title))}</span></div>
        <div class="menu-row"><span class="menu-key">Email</span><span class="menu-value">${esc(orDash(contact.email))}</span></div>
        <div class="menu-row"><span class="menu-key">Stage</span><span class="menu-value">${esc(lead.stage || 'New')}</span></div>
        <div class="menu-row"><span class="menu-key">Source</span><span class="menu-value">${esc(lead.source || '—')}</span></div>
      </div>
      ${scoresHtml(lead)}
    </div>

    <div class="menu-card pitch" style="margin-top:12px;">
      <h4>AI Sales Playbook</h4>
      <div id="drawerEnrich">${enrichmentHtml(lead)}</div>
    </div>`;

  body.querySelectorAll('[data-act]').forEach((btn) => {
    btn.addEventListener('click', (ev) => handleAction(btn.dataset.act, lead.id, ev.currentTarget));
  });
  const stageSel = body.querySelector('#drawerStage');
  if (stageSel) stageSel.addEventListener('change', () => handleStage(lead.id, stageSel.value));
}

async function handleAction(act, id, btn) {
  if (act === 'analyze') {
    const restore = busy(btn, 'Asking AI…');
    try {
      const { lead } = await api.analyze(id);
      store.upsert(lead);
      render(store.getLead(id));
      onChangeCb();
      toast('AI insights generated', 'success');
    } catch (e) {
      toast(`Analyze failed: ${e.message}`, 'error');
      restore();
    }
  } else if (act === 'outreach') {
    const restore = busy(btn, 'Drafting…');
    try {
      await api.outreach(id, { goal: 'book a 20-minute value review' });
      const { lead } = await api.getLead(id);
      store.upsert(lead);
      render(store.getLead(id));
      onChangeCb();
      toast('Outreach email drafted', 'success');
    } catch (e) {
      toast(`Outreach failed: ${e.message}`, 'error');
      restore();
    }
  } else if (act === 'delete') {
    if (!confirm(`Delete ${store.getLead(id)?.company_name || 'this lead'}?`)) return;
    try {
      await api.deleteLead(id);
      store.remove(id);
      close();
      onChangeCb();
      toast('Lead deleted', 'success');
    } catch (e) {
      toast(`Delete failed: ${e.message}`, 'error');
    }
  }
}

async function handleStage(id, stage) {
  try {
    const { lead } = await api.patchLead(id, { stage });
    store.upsert(lead);
    onChangeCb();
    toast(`Stage → ${stage}`, 'success');
  } catch (e) {
    toast(`Stage update failed: ${e.message}`, 'error');
  }
}

export function openLeadDrawer(id, { onChange } = {}) {
  const lead = store.getLead(id);
  if (!lead) return;
  onChangeCb = onChange || (() => {});
  ensureOverlay();
  render(lead);
  overlay.classList.remove('hidden');
  overlay.setAttribute('aria-hidden', 'false');
}

export default { openLeadDrawer };
