# export_params.py
#
# Dumps the *actual* trained parameters (coefficients + intercepts) of the three
# models into artifacts/model_params.json so the Node backend's pure-JS scoring
# engine can replicate ROI / waste / expansion without a Python process.
#
# This keeps the JS engine faithful to "the parameters we got from model
# training": the numbers come straight from the fitted .pkl files, not from
# hand-copied constants.
#
# Usage:
#   python export_params.py

import json
from pathlib import Path

import joblib
import numpy as np

BASE_DIR = Path(__file__).resolve().parent
ARTIFACTS_DIR = BASE_DIR / "artifacts"


def _as_list(arr):
    return [float(x) for x in np.ravel(arr)]


def _intercept(model):
    return float(np.ravel(model.intercept_)[0])


def main():
    with open(ARTIFACTS_DIR / "feature_columns.json") as f:
        feature_config = json.load(f)

    roi_model = joblib.load(ARTIFACTS_DIR / "roi_model.pkl")
    waste_model = joblib.load(ARTIFACTS_DIR / "waste_model.pkl")
    expansion_model = joblib.load(ARTIFACTS_DIR / "expansion_model.pkl")

    params = {
        "_comment": (
            "Auto-generated by export_params.py from the trained .pkl models. "
            "Do not edit by hand; re-run after retraining."
        ),
        "roi_model": {
            "type": "linear",
            "features": feature_config["roi_model"],
            "coef": _as_list(roi_model.coef_),
            "intercept": _intercept(roi_model),
        },
        "waste_model": {
            "type": "linear",
            "features": feature_config["waste_model"],
            "coef": _as_list(waste_model.coef_),
            "intercept": _intercept(waste_model),
        },
        "expansion_model": {
            "type": "logistic",
            "features": feature_config["expansion_model"],
            "coef": _as_list(expansion_model.coef_),
            "intercept": _intercept(expansion_model),
        },
    }

    out_path = ARTIFACTS_DIR / "model_params.json"
    with open(out_path, "w") as f:
        json.dump(params, f, indent=2)

    print(f"Wrote {out_path}")
    for key in ("roi_model", "waste_model", "expansion_model"):
        block = params[key]
        print(f"  {key}: {block['type']}, {len(block['features'])} features, "
              f"intercept={block['intercept']:.4f}")


if __name__ == "__main__":
    main()
